### ISSUE TITLE
XSS error

### ISSUE THREAD

**Issue by SnailDog-lua** [coffinsp/lostools#27]
```
[i] Starting scan...
[i] Checking for WAF on target URLs...
[+] No WAF detected.

[i] Payloads loaded from file.
Traceback (most recent call last):
  File "F:\lostools-main\xlsNinja.py", line 1427, in <module>
    main()
  File "F:\lostools-main\xlsNinja.py", line 1423, in main
    handle_selection(choice)
  File "F:\lostools-main\xlsNinja.py", line 1398, in handle_selection
    run_xss_scanner()
  File "F:\lostools-main\xlsNinja.py", line 869, in run_xss_scanner
    main()
  File "F:\lostools-main\xlsNinja.py", line 865, in main
    scanner.run()
AttributeError: 'MassScanner' object has no attribute 'run'
```

**Comment by Meet46** [comment]
I got the same error today i've been facing a lost issue but they are not doing anything i got this error
![Screenshot from 2024-09-12 21-44-01](https://github.com/user-attachments/assets/a01c1057-70fb-4d83-b03d-f784a601bd85)
i f anyone can help that would be great

**Comment by coffinsp** [comment]
now its fixed check upload soon the latest code

**Comment by SnailDog-lua** [comment]
Installed the new version :D
```
[i] Starting scan...
[i] Checking for WAF on target URLs...
[+] No WAF detected.
2024-09-12 22:06:15,187 - ERROR - Error loading payload file: xss.txt. Exception: 'charmap' codec can't decode byte 0x98 in position 2011: character maps to <undefined>

[!] Error loading payload file. Please check the file and try again.
```
